---
ansible_port: 22
deploy_user: "deploy"
ruby_version: "2.5.1"
bundler_version: "1.17.3"
app_name: "simple-server"
rbenv_root: "/home/{{ deploy_user }}/.rbenv"
bundle_path: "{{ rbenv_root }}/shims/bundle"
aws_deploy: false
database_name: "{{ deploy_env }}-{{ app_name }}-db"
nginx_port: 8008  # Use 8008 (HTTP Alternate) to avoid conflict with HAProxy in case deployment is on a single box
