prometheus_port: 9090
prometheus_web_listen_address: "0.0.0.0:{{ prometheus_port }}"
prometheus_targets: 
  node:
    - targets: "{{ groups.all | map('regex_replace', '^(.*)$', '\\1:9100') | list }}"

prometheus_scrape_config:
  - job_name: scrape_node_exporter
    files:
      - "{{ prometheus_config_dir }}/file_sd/node.yml"

grafana_security:
  admin_user: admin
  admin_password: admin
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: "http://{{ groups.prometheus.0 }}:{{ prometheus_port }}"
grafana_port: 3000
grafana_dashboards:
  - dashboard_id: 11074
    revision_id: 2
    datasource: "{{ grafana_datasources.0.name }}"
