ansistrano_deploy_to: "/home/deploy/apps/{{ app_name }}"
ansistrano_shared_paths:
  - .bundle
  - log
  - tmp/pids
  - tmp/cache
  - tmp/sockets
  - public/system
  - vendor/bundle
ansistrano_shared_files:
  - .env.production
ansistrano_deploy_via: "git"
ansistrano_allow_anonymous_stats: no
ansistrano_git_repo: "https://github.com/simpledotorg/simple-server.git"
ansistrano_after_symlink_shared_tasks_file: "roles/deploy/hooks/after_symlink.yml"
postgres:
  database_name: "{{ deploy_env }}-{{ app_name }}-db"

logrotate_user: "{{ deploy_user }}"
logrotate_dir: "{{ ansistrano_deploy_to }}/current/log"
logrotate_files: "{{ logrotate_dir }}/*.log"
logrotate_config_file: "/etc/logrotate.d/rails"

rsync_dir: "log_dir/*.gz"
rsync_logfile: "{{ logrotate_dir }}/rsync.log"
rsync_destination_dir: "/home/{{ deploy_user }}/logs/rails"
