- name: add ssh keys for the remote user
  become: yes
  authorized_key:
    key: "{% for key in query('fileglob', 'ssh_keys/{{ deploy_env }}/*') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}"
    user: "{{ ansible_ssh_user }}"
    exclusive: yes

- name: add ssh keys for the deploy user
  become: yes
  authorized_key:
    key: "{% for key in query('fileglob', 'ssh_keys/{{ deploy_env }}/*') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}"
    user: "{{ deploy_user }}"
    exclusive: yes

# TODO: Disable ssh password based login

# TODO:  Come back to this
#
#
# # Note: This MUST be last, otherwise if something fails we can't SSH back in as root
# - name: disable root SSH access
#   action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
#   become: yes
#   notify: restart ssh
