---
# Add key for postgresql-client
- name: Add the apt key for postgresql-client
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: "7FCC7D46ACCC4CF8"
    state: present
  become: true

- name: add repository for postgresql-client
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
  register: postgresql_client_repo
  become: true

# postgresql-client tasks
- name: install packages
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - postgresql-client
    - libpq-dev
