---
alertmanager_web_external_url: "https://{{ domain_name }}/alertmanager"
alertmanager_template_files: "roles/monitoring/files/alertmanager/templates/*.tmpl"
alertmanager_receivers:
  - name: slack
    slack_configs:
      - send_resolved: true
        channel: "#ethiopia-alerts"
        title: '{% raw %}{{ template "slack-message-title" . }}{% endraw %}'
        text: '{% raw %}{{ template "slack-message-description" . }}{% endraw %}'
    slack_test_configs:
      - send_resolved: true
        channel: "#ethiopia-test-alerts"
        title: '{% raw %}{{ template "slack-message-title" . }}{% endraw %}'
        text: '{% raw %}{{ template "slack-message-description" . }}{% endraw %}'    

alertmanager_route:
  receiver: "slack"
  routes:
    - match:
        severity: critical
      receiver: slack
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
