
---
- import_playbook: setup.yml
- import_playbook: postgres.yml
- import_playbook: redis.yml
- import_playbook: deploy.yml
- import_playbook: load_balancing.yml
- import_playbook: monitoring.yml
- import_playbook: logshipping.yml
