---
- hosts: servers
  roles:
    - { role: simple-server, tags: ['simple-server'] }
    - { role: ansistrano.deploy, tags: ['ansistrano.deploy'] }
  environment:
    RAILS_ENV: production
  remote_user: "{{ deploy_user }}"
- hosts: sidekiq
  roles:
    - { role: sidekiq, tags: ['sidekiq'] }
  remote_user: "{{ deploy_user }}"
