---
- hosts: postgres
  vars_files:
    - group_vars/postgres.yml
  roles:
    - { role: logshipping, tags: ['logshipping'] }
- hosts: servers
  vars_files:
    - group_vars/postgres.yml
  roles:
    - { role: logshipping, tags: ['logshipping'] }
- hosts: redis
  vars_files:
    - group_vars/redis.yml
  roles:
    - { role: logshipping, tags: ['logshipping'] }
