---
- name: configure the primary redis server
  hosts: redis
  roles:
    - role: davidwittman.redis
      redis_bind: 0.0.0.0
      redis_port: 6379
      redis_password: false
      redis_logfile: /var/log/redis/redis.log
