version: v1.0
name: Update QA config
blocks:
  - name: Ansible update
    task:
      jobs:
        - name: Update config
          commands:
            - checkout
            - cd ansible
            - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -v --vault-id ~/.ansible/password_file conf-update.yml -i hosts.qa
      secrets:
        - name: ansible
        - name: semaphore-deploy-key
      prologue:
        commands:
          - chmod 600 ~/.ssh/semaphore_id_rsa
          - ssh-add ~/.ssh/semaphore_id_rsa
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
