version: v1.0
name: Update Ethiopia Demo config
blocks:
  - name: Ansible update
    task:
      jobs:
        - name: Update config
          commands:
            - checkout
            - cd standalone
            - make init
            - make update-app-config hosts=ethiopia/demo password_file=~/.ansible/password_file
      secrets:
        - name: ansible
        - name: semaphore-deploy-key
      prologue:
        commands:
          - chmod 600 ~/.ssh/semaphore_id_rsa
          - ssh-add ~/.ssh/semaphore_id_rsa
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
